package com.example.administrator.mydbcontrol;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TB_CITY.
 */
public class tb_city {

    private Integer cityid;
    private String cityname;
    private String zipcode;
    private Integer provinceid;
    private Long datecreated;
    private Long dateupdated;
    private String citycode;

    public tb_city() {
    }

    public tb_city(Integer cityid, String cityname, String zipcode, Integer provinceid, Long datecreated, Long dateupdated, String citycode) {
        this.cityid = cityid;
        this.cityname = cityname;
        this.zipcode = zipcode;
        this.provinceid = provinceid;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.citycode = citycode;
    }

    public Integer getCityid() {
        return cityid;
    }

    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public String getCityname() {
        return cityname;
    }

    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public Integer getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    public Long getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Long datecreated) {
        this.datecreated = datecreated;
    }

    public Long getDateupdated() {
        return dateupdated;
    }

    public void setDateupdated(Long dateupdated) {
        this.dateupdated = dateupdated;
    }

    public String getCitycode() {
        return citycode;
    }

    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

}
