package com.example.administrator.mydbcontrol;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TB_PROVINCE.
 */
public class tb_province {

    private Integer provinceid;
    private String provincename;
    private Long datecreated;
    private Long dateupdated;
    private Integer countryid;
    private String province_code;

    public tb_province() {
    }

    public tb_province(Integer provinceid, String provincename, Long datecreated, Long dateupdated, Integer countryid, String province_code) {
        this.provinceid = provinceid;
        this.provincename = provincename;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.countryid = countryid;
        this.province_code = province_code;
    }

    public Integer getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    public String getProvincename() {
        return provincename;
    }

    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    public Long getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Long datecreated) {
        this.datecreated = datecreated;
    }

    public Long getDateupdated() {
        return dateupdated;
    }

    public void setDateupdated(Long dateupdated) {
        this.dateupdated = dateupdated;
    }

    public Integer getCountryid() {
        return countryid;
    }

    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    public String getProvince_code() {
        return province_code;
    }

    public void setProvince_code(String province_code) {
        this.province_code = province_code;
    }

}
