package com.example.administrator.mydbcontrol;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.mydbcontrol.tb_province;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TB_PROVINCE.
*/
public class tb_provinceDao extends AbstractDao<tb_province, Void> {

    public static final String TABLENAME = "TB_PROVINCE";

    /**
     * Properties of entity tb_province.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Provinceid = new Property(0, Integer.class, "provinceid", false, "PROVINCEID");
        public final static Property Provincename = new Property(1, String.class, "provincename", false, "PROVINCENAME");
        public final static Property Datecreated = new Property(2, Long.class, "datecreated", false, "DATECREATED");
        public final static Property Dateupdated = new Property(3, Long.class, "dateupdated", false, "DATEUPDATED");
        public final static Property Countryid = new Property(4, Integer.class, "countryid", false, "COUNTRYID");
        public final static Property Province_code = new Property(5, String.class, "province_code", false, "PROVINCE_CODE");
    };


    public tb_provinceDao(DaoConfig config) {
        super(config);
    }
    
    public tb_provinceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TB_PROVINCE' (" + //
                "'PROVINCEID' INTEGER," + // 0: provinceid
                "'PROVINCENAME' TEXT," + // 1: provincename
                "'DATECREATED' INTEGER," + // 2: datecreated
                "'DATEUPDATED' INTEGER," + // 3: dateupdated
                "'COUNTRYID' INTEGER," + // 4: countryid
                "'PROVINCE_CODE' TEXT);"); // 5: province_code
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TB_PROVINCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, tb_province entity) {
        stmt.clearBindings();
 
        Integer provinceid = entity.getProvinceid();
        if (provinceid != null) {
            stmt.bindLong(1, provinceid);
        }
 
        String provincename = entity.getProvincename();
        if (provincename != null) {
            stmt.bindString(2, provincename);
        }
 
        Long datecreated = entity.getDatecreated();
        if (datecreated != null) {
            stmt.bindLong(3, datecreated);
        }
 
        Long dateupdated = entity.getDateupdated();
        if (dateupdated != null) {
            stmt.bindLong(4, dateupdated);
        }
 
        Integer countryid = entity.getCountryid();
        if (countryid != null) {
            stmt.bindLong(5, countryid);
        }
 
        String province_code = entity.getProvince_code();
        if (province_code != null) {
            stmt.bindString(6, province_code);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public tb_province readEntity(Cursor cursor, int offset) {
        tb_province entity = new tb_province( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // provinceid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // provincename
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // datecreated
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // dateupdated
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // countryid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // province_code
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, tb_province entity, int offset) {
        entity.setProvinceid(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setProvincename(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDatecreated(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDateupdated(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setCountryid(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setProvince_code(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(tb_province entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(tb_province entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
